language: node_js
node_js:
  - "0.10"
env:
  - DEV=true
before_install:
  - echo 'before install'
  - npm install -g grunt-cli
  - export PATH=$PATH:`pwd`/bin
notifications:
  slack: ingenuitydesign:LRuHD7MwPHH5NFWrL3LVyKV3
after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. "; exit 0; fi
  - echo "Deploying build $TRAVIS_BUILD_NUMBER"
  - wget "http://git-deploy.ebaystratus.com/peoplemgr/?branch=$TRAVIS_BUILD_NUMBER"